"use client";
import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { link } from "fs/promises";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: {
//     default: "My Next.js App",
//     template: "%s | AshokKumarbyAshokKumar",
//   },
//   description: "Generated by create next app",
// };

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forget-password" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  console.log("Current Pathname:", pathname);

  return (
    <div>
      <div>
        {navLinks.map((link) => {
          const isActive =
            pathname === link.href ||
            (pathname.startsWith(link.href) && link.href !== "/");
          console.log(`Checking link: ${link.href}, isActive: ${isActive}`);
          return (
            <Link
              key={link.href}
              href={link.href}
              className={`mr-4 ${isActive ? "font-bold text-blue-600 " : "text-black"}`}
            >
              {link.name}
            </Link>
          );
        })}
      </div>
      {children}
    </div>
  );
}
