import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <header className="min-h-20 flex items-center justify-center bg-amber-600">
          Header
        </header>
        <div className="min-h-3/4 flex-3 flex justify-start pt-10 pl-3 bg-white flex-col font-bold text-green-500">
          {children}
        </div>
        <footer className="min-h-20 flex items-center justify-center bg-black text-2xl text-white">
          &copy; 2024 My Next.js App
        </footer>
      </body>
    </html>
  );
}
